export const AMBASSADOR_HELP = [
  {
    title: "Quem são os embaixadores",
    body: "Os embaixadores são afiliados especiais selecionados pela equipe. Para adicionar um embaixador, escolha um afiliado existente e sua categoria:\n\n- Embaixador: parceria de divulgação do Automatize.\n- Embaixador Coprodutor: parceria de divulgação que também inclui o desenvolvimento de infoprodutos com o Automatize.\n\nBernardo, administradores e integrantes autorizados das equipes compartilham o acompanhamento nesta aba.\n\nCada embaixador tem um responsável pela publicidade. Nos Embaixadores\nCoprodutores, há também um responsável pela coprodução; pode ser a mesma pessoa\nnas duas trilhas. Use o filtro de responsável para acompanhar as tarefas de\ncada integrante.\n\nTodos os integrantes autorizados na aba podem atualizar as duas trilhas,\nmesmo sem serem os responsáveis. O histórico registra quem alterou e quando.",
  },
  {
    title: "Primeiros passos",
    body: "Todas as etapas ficam visíveis e suas datas podem ser planejadas antecipadamente.\nPara concluir uma etapa, conclua primeiro a anterior da mesma trilha. Após a\nformalização, publicidade e coprodução avançam de forma independente.\n\nTodos os prazos são contados em dias corridos, incluindo fins de semana e feriados.\n\nAo concluir uma tarefa, a data sugerida é hoje. Se ela aconteceu antes, informe\na data real. Isso vale também para assinatura do contrato, publicação e Start.\nOs prazos dependentes partem da data real de realização. Por exemplo,\num onboarding realizado na segunda e registrado na quinta gera a checagem para\na segunda seguinte.\n\nSe uma data de realização for corrigida, apenas os prazos das tarefas ainda\npendentes serão recalculados. Tarefas já concluídas ficam preservadas, e a\ncorreção fica registrada no histórico.\n\nPara desmarcar uma etapa, nenhuma etapa posterior que depende dela pode estar\nconcluída. Se houver, desfaça essas conclusões primeiro. O histórico preserva\nas alterações. Corrigir apenas uma data não exige desfazer tarefas realizadas.\n\n1. Formalização: marque como concluída depois da assinatura do contrato.\n2. Reunião de onboarding: agende a reunião e marque como concluída depois de realizá-la.\n3. Checagem: colete o feedback sete dias depois da conclusão do onboarding. Conclua quando a equipe decidir seguir para a primeira publicação, sem uma meta automática de ROAS ou vendas. Se ainda houver ajustes necessários, mantenha pendente e registre o motivo nas observações.\n4. Data da publi: depois da checagem, informe a data da primeira publicação.\n5. Enviar briefing: acompanhe o prazo de sete dias antes da publicação. Se a data da publi mudar, o prazo do briefing pendente será atualizado. Quando faltarem menos de sete dias para a publi, o briefing fica para hoje, sem bloquear o agendamento.\n6. Publi feita: no dia da publicação, fica disponível a opção de marcar sua conclusão. A passagem da data não confirma que a publicação aconteceu.",
  },
  {
    title: "Liberação do Starter",
    body: "O botão Liberar Starter permite iniciar a liberação manual do benefício para o\nembaixador. Concluir o onboarding apenas registra a reunião; marcar ou corrigir\numa tarefa não libera nem altera o acesso automaticamente.\n\nAo liberar, Bernardo escolhe a data de vencimento. Essa data fica visível na\nficha para acompanhar o benefício e renová-lo manualmente conforme o combinado.\nA parceria ativa não renova a gratuidade automaticamente.\n\nSomente Bernardo e administradores podem liberar ou prorrogar o Starter. Os\ndemais integrantes autorizados podem consultar o vencimento.\n\nA gratuidade inclui 250 créditos na liberação e, depois, no mesmo dia dos meses\nseguintes enquanto estiver válida. Por exemplo, uma liberação em 21 de setembro\ngera a próxima concessão em 21 de outubro, se o benefício continuar válido.\nAlterar o vencimento não concede créditos extras nem reinicia o ciclo.\n\nSe a gratuidade vencer e for renovada depois, o acesso volta até o novo\nvencimento. Os créditos retornam na próxima data do calendário original, sem\nconcessão extra na renovação nem reposição dos ciclos em que o benefício estava\nvencido.\n\nEsse calendário de créditos é independente das tarefas de publicação, que\nrenovam no dia 1º de cada mês.\n\nSe o embaixador já tiver uma assinatura paga ativa, o botão de liberação fica\nbloqueado. Encaminhe o caso para um administrador revisar a assinatura antes de\nconceder a gratuidade.",
  },
  {
    title: "Publicações mensais",
    body: "A recorrência começa no primeiro dia do mês seguinte à conclusão da primeira publicação. O processo inicial não reinicia todo mês.\n\nExemplo: onboarding em 28 de setembro, feedback em 5 de outubro e primeira publi concluída em 15 de outubro. O primeiro ciclo mensal começa em 1º de novembro.\n\nVale a data em que a publicação aconteceu: uma publi feita em 30 de setembro e\nregistrada em 2 de outubro inicia a recorrência em outubro.\n\nA cada dia 1, abre um novo ciclo para definir a data da publicação do mês, enviar o briefing e registrar a publicação realizada.\n\nCada mês mantém seu próprio histórico. Tarefas antigas não são apagadas ou desmarcadas. Se a publi de setembro não foi realizada, ela continua atrasada enquanto a equipe organiza a de outubro.\n\nA checagem de feedback é obrigatória somente no processo inicial. Feedbacks\nposteriores podem ser registrados em observações livres, sem outra tarefa\nmensal obrigatória de checagem de resultados.",
  },
  {
    title: "Encerramento da parceria",
    body: "Ao encerrar a parceria, o acompanhamento deixa de gerar novos ciclos de\npublicação. O histórico e as pendências existentes ficam preservados.\n\nO Starter já concedido, incluindo os créditos mensais, continua até o vencimento\nescolhido. O encerramento não renova o benefício nem antecipa sua expiração.",
  },
  {
    title: "Coprodução em paralelo",
    body: "Escolher a categoria Embaixador Coprodutor abre o acompanhamento dessa trilha.\nO cadastro de Expert e as condições de venda dos produtos são definidos\nseparadamente, no fluxo já existente.\n\nA categoria pode ser alterada depois do cadastro. Ao virar Embaixador\nCoprodutor, abre a trilha de coprodução. Ao voltar para Embaixador, essa trilha\né arquivada e seu histórico fica preservado. A publicidade continua de onde\nestava, sem reiniciar.\n\nPara Embaixadores Coprodutores, depois da formalização também começa uma trilha própria:\n\n1. Reunião de brainstorm: entender produtos, segmento e ideias.\n2. Apresentação do projeto: prevista para sete a dez dias depois do brainstorm.\n3. Materiais de divulgação e produto: acompanhe landing page, VSL, criativos e produto em um checklist. Marque cada item como concluído ou Não se aplica. A etapa fica concluída quando não houver itens pendentes.\n4. Start: registre a data e conclua a etapa quando acontecer o lançamento do projeto e o início das vendas. Esse registro não publica produtos nem campanhas automaticamente.\n\nPublicidade e coprodução são acompanhadas em campos separados e podem avançar em paralelo, com equipes diferentes.",
  },
];
