"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import type { CustomAudienceView } from "@/lib/meta-business/marketing/audiences";

type Review = { ok: true; message: string; preflight: { name?: string; retentionDays?: number; knownUses: unknown[]; lookalikeAudienceIds: string[]; coverage: string; limitations: string[]; confirmationToken: string } };
export function AudienceDeletionControl({ audience, accountId, userId, onDeleted }: { audience: CustomAudienceView; accountId: string; userId: string; onDeleted: () => void }) {
  const [open, setOpen] = useState(false); const [review, setReview] = useState<Review | null>(null); const [error, setError] = useState<string | null>(null);
  const request = async (action: "delete-review" | "delete-confirm") => { setError(null); const response = await fetch(`/api/meta-marketing/${accountId}/audiences?userId=${encodeURIComponent(userId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, audienceId: audience.id, confirmationToken: review?.preflight.confirmationToken }) }); const result = await response.json() as Review & { error?: string; issues?: Array<{ message?: string }> }; if (!response.ok || !result.ok) { setError(result.error ?? result.issues?.[0]?.message ?? "Não foi possível excluir o público."); return; } if (action === "delete-review") setReview(result); else { setOpen(false); setReview(null); onDeleted(); } };
  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); if (!next) setReview(null); }}><DialogTrigger asChild><Button size="sm" variant="destructive">Excluir na Meta</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Excluir <em className="font-ivymode italic">público na Meta</em></DialogTitle><DialogDescription>{review?.message ?? `Ação permanente para “${audience.name ?? audience.id}”, na conta ${accountId}.`}</DialogDescription></DialogHeader>{review ? <div className="space-y-3 text-sm"><p>Permanência: {review.preflight.retentionDays === undefined ? "Não informada" : `${review.preflight.retentionDays} dias`}</p><p>Usos conhecidos: {review.preflight.knownUses.length}. Lookalikes dependentes: {review.preflight.lookalikeAudienceIds.length}.</p><p role="status">Inventário: {review.preflight.coverage}. {review.preflight.limitations.join(" ")}</p>{review.preflight.lookalikeAudienceIds.length ? <p role="alert" className="text-destructive">A origem está bloqueada até o tratamento individual dos dependentes.</p> : <Button onClick={() => void request("delete-confirm")}>Confirmar exclusão permanente</Button>}</div> : <Button onClick={() => void request("delete-review")}>Revisar impacto antes de excluir</Button>}{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</DialogContent></Dialog>;
}
