"use client";

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { assessLookalikeSource } from "@/lib/meta-business/marketing/audiences/lookalike";
import type { CustomAudienceView } from "@/lib/meta-business/marketing/audiences/read";

type Review = { confirmationToken: string; source: { id: string; name?: string }; formation: { country: string; percentage: number }; notice: string };

export function LookalikeAudienceCreator({ accountId, userId, audiences, onSaved }: { accountId: string; userId: string; audiences: CustomAudienceView[]; onSaved: () => void }) {
  const sources = useMemo(() => audiences.filter((audience) => assessLookalikeSource(audience).ok), [audiences]);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [originAudienceId, setOriginAudienceId] = useState(""); const [country, setCountry] = useState("BR"); const [percentage, setPercentage] = useState("1"); const [review, setReview] = useState<Review | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const request = async (action: "lookalike-review" | "lookalike-confirm") => { setSaving(true); setError(null); try { const response = await fetch(`/api/meta-marketing/${accountId}/audiences?userId=${encodeURIComponent(userId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, originAudienceId, name, description: description || undefined, country, percentage: Number(percentage), ...(review ? { confirmationToken: review.confirmationToken } : {}) }) }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.message ?? "N\u00e3o foi poss\u00edvel criar o p\u00fablico semelhante."); if (action === "lookalike-review") setReview(body as Review); else { setReview(null); setName(""); setDescription(""); setOriginAudienceId(""); onSaved(); } } catch (caught) { setError(caught instanceof Error ? caught.message : "N\u00e3o foi poss\u00edvel criar o p\u00fablico semelhante."); } finally { setSaving(false); } };
  return <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">Criar p\u00fablico semelhante</summary><div className="mt-4 grid gap-3 md:grid-cols-2"><label>Nome<input className="mt-1 w-full rounded border p-2" value={name} onChange={(event) => { setName(event.target.value); setReview(null); }} /></label><label>Descri\u00e7\u00e3o (opcional)<input className="mt-1 w-full rounded border p-2" value={description} onChange={(event) => { setDescription(event.target.value); setReview(null); }} /></label><label>Origem eleg\u00edvel<select className="mt-1 w-full rounded border p-2" value={originAudienceId} onChange={(event) => { setOriginAudienceId(event.target.value); setReview(null); }}><option value="">Selecione</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.name ?? source.id}</option>)}</select></label><label>Pa\u00eds (ISO-2)<input className="mt-1 w-full rounded border p-2" value={country} onChange={(event) => { setCountry(event.target.value); setReview(null); }} /></label><label>Tamanho do semelhante (%)<input className="mt-1 w-full rounded border p-2" inputMode="numeric" value={percentage} onChange={(event) => { setPercentage(event.target.value); setReview(null); }} /></label></div><p className="mt-3 text-xs text-muted-foreground">Brasil e 1% s\u00e3o valores iniciais. O percentual define o tamanho do p\u00fablico semelhante, n\u00e3o a confian\u00e7a ou a taxa de correspond\u00eancia. A Meta decide a elegibilidade final.</p>{review ? <div className="mt-3 rounded border p-3 text-sm"><p>Revise: {review.source.name ?? review.source.id} \u00b7 {review.formation.country} \u00b7 {review.formation.percentage}%.</p><p className="mt-1 text-xs text-muted-foreground">{review.notice}</p><Button className="mt-3" disabled={saving} onClick={() => void request("lookalike-confirm")}>{saving ? "Criando..." : "Confirmar cria\u00e7\u00e3o"}</Button></div> : <Button className="mt-3" disabled={saving || !sources.length} onClick={() => void request("lookalike-review")}>{saving ? "Revisando..." : "Revisar cria\u00e7\u00e3o"}</Button>}{error ? <p role="alert" className="mt-2 text-sm text-destructive">{error}</p> : null}{!sources.length ? <p className="mt-2 text-sm text-muted-foreground">Nenhuma origem eleg\u00edvel acess\u00edvel nesta p\u00e1gina.</p> : null}</details>;
}
