"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { parseWebsiteAudienceRule } from "@/lib/meta-business/marketing/audiences/website";
import type { CustomAudienceView } from "@/lib/meta-business/marketing/audiences/types";
type Source = { id: string; name?: string };
export function WebsiteAudienceEditor({ accountId, userId, audience, onSaved }: { accountId: string; userId: string; audience?: CustomAudienceView; onSaved: () => void }) {
  const current = audience?.rule ? parseWebsiteAudienceRule(audience.rule) : null;
  const [sources, setSources] = useState<Source[]>([]), [guidance, setGuidance] = useState<string | null>(null), [name, setName] = useState(audience?.name ?? ""), [pixelId, setPixelId] = useState(current?.pixelId ?? ""), [criterion, setCriterion] = useState(current?.criterion ?? "visitors"), [retentionDays, setRetentionDays] = useState(current?.retentionDays ? String(current.retentionDays) : ""), [url, setUrl] = useState(current?.url ?? ""), [error, setError] = useState<string | null>(null), [saving, setSaving] = useState(false);
  useEffect(() => { void fetch(`/api/meta-marketing/${accountId}/audiences?userId=${encodeURIComponent(userId)}&sources=website`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Não foi possível consultar as fontes do site."); setSources(body.sources ?? []); setGuidance(body.guidance ?? null); setPixelId((value) => value || body.sources?.[0]?.id || ""); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Não foi possível consultar as fontes do site.")); }, [accountId, userId]);
  if (audience && !current) return null;
  const save = async () => { const days = Number(retentionDays); if (!name.trim() || !pixelId || !Number.isInteger(days) || (criterion === "url" && !url.trim())) { setError("Informe nome, fonte, período e o filtro exigido."); return; } setSaving(true); setError(null); try { const response = await fetch(`/api/meta-marketing/${accountId}/audiences?userId=${encodeURIComponent(userId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: audience ? "website-update" : "website-create", audienceId: audience?.id, name, pixelId, criterion, retentionDays: days, url }) }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.message ?? "Não foi possível salvar o público."); onSaved(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível salvar o público."); } finally { setSaving(false); } };
  return <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">{audience ? "Editar regra do site" : "Criar público do site"}</summary><div className="mt-4 grid gap-3 md:grid-cols-2"><label>Nome<input className="mt-1 w-full rounded border p-2" value={name} onChange={(event) => setName(event.target.value)} /></label><label>Fonte com atividade<select className="mt-1 w-full rounded border p-2" value={pixelId} onChange={(event) => setPixelId(event.target.value)}>{sources.map((source) => <option key={source.id} value={source.id}>{source.name ?? source.id}</option>)}</select></label><label>Critério<select className="mt-1 w-full rounded border p-2" value={criterion} onChange={(event) => setCriterion(event.target.value as typeof criterion)}><option value="visitors">Todos os visitantes registrados</option><option value="url">Páginas por URL</option><option value="event" disabled>Evento registrado (aguarda observação)</option></select></label><label>Período (1–180 dias)<input className="mt-1 w-full rounded border p-2" value={retentionDays} onChange={(event) => setRetentionDays(event.target.value)} /></label>{criterion === "url" ? <label className="md:col-span-2">URL contém<input className="mt-1 w-full rounded border p-2" value={url} onChange={(event) => setUrl(event.target.value)} /></label> : null}</div><p className="mt-3 text-xs text-muted-foreground">Fonte, atividade e disponibilidade são fatos distintos. O período é uma janela móvel; a Meta define o preenchimento histórico.</p>{guidance ? <p role="status" className="mt-2 text-sm text-muted-foreground">{guidance}</p> : null}{error ? <p role="alert" className="mt-2 text-sm text-destructive">{error}</p> : null}<Button className="mt-3" disabled={saving || !sources.length} onClick={save}>{saving ? "Salvando..." : audience ? "Salvar regra" : "Criar público"}</Button></details>;
}
